version: '3'

services:
  wireguard:
    container_name: wireguard
    build: .
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules
      - wireguard-conf:/etc/wireguard
    cap_add:
      - net_admin 
      - sys_module
    ports:
      - 51820:51820/udp
    env_file:
      - ./wireguard.env

volumes:
  wireguard-conf:
